org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=26.1.2
loader_version=0.15.11
fabric_version=0.102.0+1.21.2
fabric_kotlin_version=1.12.0+kotlin.2.0.20

maven_group=com.nikoo
archives_base_name=niko-client
mod_version=1.0.0
mod_name=Niko Client
mod_description=A client-side Fabric mod with inventory macro system for vanilla Minecraft
